### ISSUE TITLE
Heroku pay to use update

### ISSUE THREAD

**Issue by tnfssc** [RaviVanam/yelp-camp#1]
Heroku released a [blog post](https://blog.heroku.com/next-chapter) saying that they will stop providing their free services. Will that be a problem for the hosted version of this application?

**Comment by RaviVanam** [comment]
> Heroku released a [blog post](https://blog.heroku.com/next-chapter) saying that they will stop providing their free services. Will that be a problem for the hosted version of this application?

yes but it won't effect the data as it's stored in Mongo atlas. I'll rehost this through other services in the future
